# Generated by Django 4.2.7 on 2025-11-14 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=100)),
                ('task_description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('phase1_running', 'Phase 1 Running'), ('phase1_done', 'Phase 1 Done'), ('phase2_running', 'Phase 2 Running'), ('phase2_done', 'Phase 2 Done'), ('phase3_running', 'Phase 3 Running'), ('phase3_done', 'Phase 3 Done'), ('phase4_running', 'Phase 4 Running'), ('phase4_done', 'Phase 4 Done'), ('phase5_running', 'Phase 5 Running'), ('completed', 'Completed'), ('error', 'Error')], default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=255)),
                ('product_name', models.CharField(blank=True, max_length=255, null=True)),
                ('evidence_url', models.URLField(blank=True, null=True)),
                ('source', models.CharField(default='discovery', max_length=255)),
                ('status', models.CharField(default='discovered', max_length=50)),
                ('aps_2024', models.FloatField(default=0.7, null=True)),
                ('aps_2025', models.FloatField(default=0.8, null=True)),
                ('aps_2026', models.FloatField(default=0.9, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='pipeline.task')),
            ],
            options={
                'db_table': 'vendors',
            },
        ),
        migrations.CreateModel(
            name='ValidationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(max_length=50)),
                ('validation_type', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('details', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_logs', to='pipeline.task')),
            ],
            options={
                'db_table': 'validation_logs',
            },
        ),
        migrations.CreateModel(
            name='Subtask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtask_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('time_percent', models.FloatField()),
                ('importance', models.FloatField()),
                ('ai_applicable', models.CharField(max_length=20)),
                ('onet_weight', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='pipeline.task')),
            ],
            options={
                'db_table': 'subtasks',
            },
        ),
        migrations.CreateModel(
            name='FinalAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('automation_2024', models.FloatField()),
                ('automation_2025', models.FloatField()),
                ('automation_2026', models.FloatField()),
                ('hrf_scores', models.JSONField()),
                ('rpi_score', models.FloatField()),
                ('recommendations', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('best_vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pipeline.vendor')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='final_analysis', to='pipeline.task')),
            ],
            options={
                'db_table': 'final_analysis',
            },
        ),
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('aps_score', models.FloatField()),
                ('capability_description', models.TextField()),
                ('source', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='pipeline.vendor')),
            ],
            options={
                'db_table': 'timeline',
                'unique_together': {('vendor', 'phase', 'year')},
            },
        ),
        migrations.CreateModel(
            name='CapabilityMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_handle', models.CharField(max_length=20)),
                ('aps_2024', models.FloatField(blank=True, null=True)),
                ('aps_2025', models.FloatField(blank=True, null=True)),
                ('aps_2026', models.FloatField(blank=True, null=True)),
                ('improvement_rate', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subtask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pipeline.subtask')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capability_mappings', to='pipeline.task')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pipeline.vendor')),
            ],
            options={
                'db_table': 'capability_mapping',
                'unique_together': {('vendor', 'subtask')},
            },
        ),
    ]
